<html>
<head>
    <title>
        Hello World Title
    </title>
    <style type="text/css">
         <#include "css/main.css">
    </style>
</head>
<body>
<#include "header.ftlh">
<div id = "subsection_1">
<div id="heading_1">
    System Status
</div>
<div id = "heading_1_content" class = "alternate_colored_list">
    <ul>
    <li>
    <span class = "row_item_key">Environment</span>
    <span class = "row_item_value">test</span>
    </l1>

    <li>
        <span class = "row_item_key">Data center</span>
        <span class = "row_item_value">default</span>
    </l1>


    </ul>
</div>

<div id = "heading_2_content" class = "alternate_colored_list">
    <ul>
    <li>
        <span class = "row_item_key">Environment</span>
        <span class = "row_item_value">test</span>
    </l1>

    <li>
        <span class = "row_item_key">Data center</span>
        <span class = "row_item_value">default</span>
    </l1>
    <li>
        <span class = "row_item_key">Data center</span>
        <span class = "row_item_value">default</span>
    </l1>
    <li>
        <span class = "row_item_key">Data center</span>
        <span class = "row_item_value">default</span>
    </l1>
    <li>
        <span class = "row_item_key">Data center</span>
        <span class = "row_item_value">default</span>
    </l1>

    </ul>
</div>
</div>
</body>
</html>